/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SearchBar.module.css";

const SearchBar = () => {
  return (
    <section className={styles.searchSection}>
      <div className={styles.searchOptions}>
        <input
          type="text"
          placeholder="Keywords/job title"
          className={styles.searchInput}
        />
        <input
          type="text"
          placeholder="Location"
          className={styles.searchInput}
        />
        <select className={styles.searchInput}>
          <option value="">Distance</option>
        </select>
        <button className={styles.findJobsButton}>Find jobs</button>
      </div>
      <div className={styles.searchKeywords}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/e96845e085acbb98ebfbb279740c92c533c61eae0030c553d6a6d2f2c39c48f4?placeholderIfAbsent=true&apiKey=8a1e4083f58f4588a29f4fafd0874267"
          alt=""
          className={styles.searchIcon}
        />
        <span className={styles.searchPlaceholder}>
          Search keywords or job title
        </span>
      </div>
    </section>
  );
};

export default SearchBar;
