/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./JobDetails.module.css";

function JobDetails() {
  return (
    <section className={styles.jobDetailsSection}>
      <aside className={styles.sidebar}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/cad3470c0d5974e4b9cae5b9507289cfeebcee245c62119cc13b72da2a33571d?placeholderIfAbsent=true&apiKey=8a1e4083f58f4588a29f4fafd0874267"
          alt="Company logo"
          className={styles.companyLogo}
        />
      </aside>
      <article className={styles.jobContent}>
        <div className={styles.jobHeader}>
          <h2 className={styles.jobTitle}>Job Title</h2>
          <p className={styles.jobMeta}>
            Full Time/Permanent - Company / Location
          </p>
          <p className={styles.jobDescription}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Bibendum
            vitae dictumst sit vitae, mi imperdiet sit. Lectus eleifend aliquam
            nibh mauris, pretium. Lectus magnis lorem massa urna felis porta.
          </p>
          <button className={styles.applyButton}>Apply Now</button>
        </div>
        <h3 className={styles.descriptionTitle}>Description</h3>
        <div className={styles.fullDescription}>
          {/* Full job description content would go here */}
        </div>
      </article>
    </section>
  );
}

export default JobDetails;
